FROM node:22.7-slim

RUN apt-get update
RUN apt-get install ca-certificates -y

WORKDIR /app

COPY package.json tsconfig.json /app/

RUN npm install -y

COPY . /app/

ARG SENTRY_AUTH_TOKEN

RUN npx next telemetry disable

RUN npm run build

CMD ["npm", "run", "start"]

