FROM node:22.7-slim

RUN apt-get update
RUN apt-get install ca-certificates -y

WORKDIR /app

COPY package.json tsconfig.json /app/

RUN npm install -y --omit=dev

COPY . /app/

CMD ["npm", "run", "start"]

