FROM node:22.7-slim

RUN apt-get update
RUN apt-get install ca-certificates -y

WORKDIR /app

COPY package.json tsconfig.json /app/

RUN npm install -y

COPY . /app/

RUN npx next telemetry disable

RUN --mount=type=secret,id=sentry_auth \
    export SENTRY_AUTH_TOKEN=$(cat /run/secrets/sentry_auth) && \
    npm run build

CMD ["npm", "run", "start"]

