FROM python:3.13.3-alpine

ENV PYTHONUNBUFFERED=1
ENV POETRY_VIRTUALENVS_CREATE=false

WORKDIR /app

COPY pyproject.toml /app/

RUN python -mpip install --upgrade pip --root-user-action=ignore
RUN python -mpip install poetry && poetry install --only main

COPY . /app/src

WORKDIR /app/src

RUN rm Dockerfile Dockerfile.prod pyproject.toml