import os

PROJECT_DOMAIN = os.getenv("PROJECT_DOMAIN")
REGISTRY_USERNAME = os.getenv("REGISTRY_USERNAME")
REGISTRY_PASSWORD = os.getenv("REGISTRY_PASSWORD")
REGISTRY_HOSTNAME = os.getenv("REGISTRY_HOSTNAME")

