#!/usr/bin/env bash

set -e
set -a

PROJECT_DIR=$(pwd)
DEPLOY_DIR="$PROJECT_DIR/deploy"

DEV_COMPOSE="docker compose -f $DEPLOY_DIR/compose/common.yml -f $DEPLOY_DIR/compose/dev.yml --env-file=$DEPLOY_DIR/env.base --env-file=$DEPLOY_DIR/env.dev"
DEV_SUPERUSER_PASSWORD="devpass"
PROJECT_TEMPLATE_DIR="$HOME/projects/project_template"

source $PROJECT_DIR/.env
source $DEPLOY_DIR/env.base
source $DEPLOY_DIR/env.dev

if [ $1 = "django" ]; then
    $DEV_COMPOSE run --rm django python manage.py "${@:2}"
elif [ $1 = "sh" ]; then
    $DEV_COMPOSE exec $2 bash
elif [ $1 = "test" ]; then
    $DEV_COMPOSE run --rm django pytest
elif [ $1 = "format" ]; then
    $DEV_COMPOSE run --rm django sh -c 'isort . && black .'
elif [ $1 = "tmux" ]; then
    ./dev-scripts/tmux_dev.sh
elif [ $1 = "devsuperuser" ]; then
    $DEV_COMPOSE run --rm django sh -c "export DJANGO_SUPERUSER_PASSWORD='devpass' && python manage.py createsuperuser --noinput --username $2 --email $2@$2.com"
elif [ $1 = "buildtest" ]; then
    docker build . --file=dev-scripts/Dockerfile.playwright --tag $PROJECT_NAME-playwright
elif [ $1 = "runtest" ]; then
    docker run -it --rm --hostname=$PROJECT_NAME-tests --name=$PROJECT_NAME-tests -v .:/app/src --ipc=host --network=$PROJECT_NAME $PROJECT_NAME-playwright npx playwright test
elif [ $1 = "generatetypes" ]; then
    $DEV_COMPOSE exec nextjs npx -y openapi-typescript@7.4.1 http://django:8000/api/openapi.json --output api/apiTypes.ts
elif [ $1 = "deploystage" ]; then
    $DEPLOY_DIR/deploy.sh $DEPLOY_DIR/env.stage
elif [ $1 = "deployprod" ]; then
    $DEPLOY_DIR/deploy.sh $DEPLOY_DIR/env.prod
elif [ $1 = "djangoprod" ]; then
    source $DEPLOY_DIR/env.prod
    ssh root@$PROJECT_DOMAIN "cd /app/$PROJECT_NAME && ./manage_prod.sh ${@:2}"
elif [ $1 = "logsprod" ]; then
    source $DEPLOY_DIR/env.prod
    ssh root@$PROJECT_DOMAIN "docker service logs ${PROJECT_NAME}_${2}"
elif [ $1 = "gencerts" ]; then
    $DEPLOY_DIR/generate_certs.sh ${PROJECT_NAME} ${PROJECT_DOMAIN}
    sudo security add-trusted-cert -d -r trustRoot -k /Library/Keychains/System.keychain $DEPLOY_DIR/ssl/$PROJECT_NAME.crt
elif [ $1 = "initinfra" ]; then
    source $DEPLOY_DIR/env.prod
    python3 $DEPLOY_DIR/do/do_init.py
elif [ $1 = "initprod" ]; then
    source $DEPLOY_DIR/env.prod
    $DEPLOY_DIR/production_setup.sh $PROJECT_DOMAIN
elif [ $1 = "updatetemplate" ]; then
    source $DEPLOY_DIR/env.prod
    $PROJECT_TEMPLATE_DIR/update_template.sh -t django_nextjs_template -n $PROJECT_NAME -r $PROJECT_DIR -d $PROJECT_DOMAIN
elif [ $1 = "updatesubmodules" ]; then
    git submodule init
    git submodule update --remote
elif [ $1 = "dumpdev" ]; then
    $DEV_COMPOSE exec postgres pg_dump --username=$PROJECT_NAME $PROJECT_NAME > dump.sql
else
    $DEV_COMPOSE $@
fi
