name: balancer

services:
  nginx:
    image: "nginx:1.27.2-alpine-slim"
    container_name: nginx
    volumes:
      - ${NGINX_CONFIG_DIR}:/etc/nginx/conf.d
      - ${SSL_CERTS_DIR}:/app/ssl
    ports:
      - "80:80"
      - "443:443"
    networks:
      - devnet

networks:
  devnet:
    name: devnet