
services:
  nginx:
    image: "nginx:1.27.2-alpine-slim"
    volumes:
      - /app/certbot/certificates:/etc/letsencrypt
      - /app/certbot/challenge:/var/www/certbot
      - /app/balancer/conf:/etc/nginx/conf.d
    ports:
      - "80:80"
      - "443:443"
    networks:
      - prodnet

networks:
  prodnet:
    name: prodnet